### Create Task Template
POST http://localhost:3001/v1/task-template/create
content-type: application/json

{
    "taskName": "Test Task 1",
    "creatorId": "verkho404@gmail.com",
    "stage": 1,
    "taskType": 0
}

### Create Task Template 2 b75f74e9-9bcd-40b4-ab9d-8084a5f3b0b8
POST http://localhost:3001/v1/task-template/create
content-type: application/json

{
    "taskName": "Test Task 2",
    "creatorId": "verkho404@gmail.com",
    "stage": 1,
    "taskType": 1,
    "prevTtid": "0d181905-98d4-427a-98f5-3d83d4007e0a",
    "nextTtid": null
}

### Create Task Template 1.5
POST http://localhost:3001/v1/task-template/create
content-type: application/json

{
    "taskName": "Test Task 1.5",
    "creatorId": "verkho404@gmail.com",
    "stage": 1,
    "taskType": 2,
    "prevTtid": "2fb3955e-ce61-46ff-b841-518db7e7e5d7",
    "nextTtid": "7f20339d-fa18-475a-bd8e-19f21a42fb3e"
}


### Read Task Template By Stage
POST http://localhost:3001/v1/task-template/read/stage
content-type: application/json

{
    "stage": 1,
    "creatorId": "verkho404@gmail.com"
}

### Delete Task Template
POST http://localhost:3001/v1/task-template/delete
content-type: application/json

{
    "ttid": "2338b625-c902-43c2-b5c2-1b77967789a4"
}

### Create Task Template With Template Objects
POST http://localhost:3001/v1/task-template/create/template
content-type: application/json

{
    "taskName": "Confirm case details",
    "taskType": 1,
    "templateObjs": [
        {
            "templateTitle": "[IMPORTANT] FEK Notice to Purchaser",
            "templateContent": "Dear {{customerName}},\n\nWe are writing to inform you that your order has been confirmed. Please find the details below:\n\nOrder ID: {{orderId}}\nOrder Date: {{orderDate}}\n\nThank you for shopping with us.\n\nSincerely,\n{{companyName}}"
        }
    ]
}

### Get Task Templates
POST http://localhost:3001/v1/task-template/read
content-type: application/json

{
    "taskName": "Confirm case details"
}


### Delete Task Template
POST http://localhost:3001/v1/task-template/delete
content-type: application/json

{
    "ttid": "a7640332-b8ff-4635-a1fe-272b51ecde91"
}

### Create Default Task Templates
POST http://localhost:3001/v1/task-template/create/default
content-type: application/json

{
    "creatorId": "verkho404@gmail.com"
}