### Register a new contact
POST http://localhost:3001/v1/contact/register
content-type: application/json

{
    "tags": ["Broker", "Realtor"],
    "firstName": "Lawson",
    "lastName": "Wu",
    "company": "RichTech",
    "position": "CTO",
    "email": "test@gmail.com",
    "cellNumber": "0912345678",
    "wechatAccount": "lawsonwu",
    "note": "This is a test contact."
}


### Query contact by contactId
GET http://localhost:3001/v1/contact/b6f6c07e-305d-4e91-8a2c-50c4369ba0d1


### Query all contacts
GET http://localhost:3001/v1/contact/all


### Query contact by keyword
POST http://localhost:3001/v1/contact/query
content-type: application/json

{
    "keyword": "RichTech"
}


### Query contact by contactType
POST http://localhost:3001/v1/contact/query/tag
content-type: application/json

{
    "tag": "Client"
}


### Query contact by case and contactType
POST http://localhost:3001/v1/contact/query/caseandtag
content-type: application/json

{
    "caseId": "7097fce5-cab3-4fb7-8280-bcd1aac67a40",
    "tag": "Client"
}


### Update a contact
POST http://localhost:3001/v1/contact/update
content-type: application/json

{
    "contactId": "df171ae8-6c0d-48d3-8cde-d0e7c0d1a07e",
    "contactType": 0,
    "tags": ["Broker"],
    "firstName": "Larry",
    "lastName": "Woooo",
    "company": "RichTech",
    "position": "Intern",
    "email": "otter@gmail.com",
    "cellNumber": "0912345678",
    "mailingAddress": "Carrollton TX 75006-2917",
    "wechatAccount": "lawsonwu",
    "note": "This is a test contact."
}


### Update
POST https://api.richcrm.org/v1/contact/update
content-type: application/json

{
    "contactId": "0d97f516-4b61-414f-92c3-16b76b22c059",
    "firstName": "Lawson",
    "lastName": "Wu",
    "tags": ["Attorney"]
}


### Delete a contact
POST http://localhost:3001/v1/contact/delete
content-type: application/json

{
    "contactId": "8905a0b8-7848-4b9c-b149-d59f4185921c"
}