### Create Task
POST http://localhost:3001/v1/task/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IlRlc3QgQWRtaW4iLCJSb2xlIjowLCJFbWFpbEFkZHJlc3MiOiJ0ZXN0MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzc2MDIxNjcsImV4cCI6MTczNzYwNTc2N30.9MTYaZqJ6BufgkDbCR0-8XH6UNBvrjZaBYyveTQfSwE

{
    "stageId": "aa7a5fd4-2750-4c3c-ab34-8d4b92601744",
    "taskType": 0,
    "name": "Test Task 1",
    "status": 0,
    "templates": ["Default Template", "Default Template"]
}

### Get Task by Task ID
GET http://localhost:3001/v1/task/4ae1e884-f8fc-4ad7-8e8b-ff17e6f9ae5f


### Update Task by Task ID
POST http://localhost:3001/v1/task/update
content-type: application/json

{
    "taskId": "491ea7bb-def5-4227-94f1-551b97244b38",
    "status": 2,
    "templates": []
}

### Delete Task by Task ID
POST http://localhost:3001/v1/task/delete
content-type: application/json

{
    "taskId": "491ea7bb-def5-4227-94f1-551b97244b38"
}
