### Create Task
POST http://localhost:3001/v1/task/create
content-type: application/json

{
    "stageId": "ab4c7c67-66c7-483d-a34f-d3afdbe17086",
    "taskType": 1,
    "name": "Customized Taskkkk",
    "status": 1,
    "templates": ["Default Template", "Default Template"]
}

### Get Task by Task ID
GET http://localhost:3001/v1/task/e3374906-86e3-462b-bf63-9a89698cfa5d


### Update Task by Task ID
POST http://localhost:3001/v1/task/update
content-type: application/json

{
    "taskId": "491ea7bb-def5-4227-94f1-551b97244b38",
    "status": 2,
    "templates": []
}

### Delete Task by Task ID
POST http://localhost:3001/v1/task/delete
content-type: application/json

{
    "taskId": "491ea7bb-def5-4227-94f1-551b97244b38"
}
