### Create Stage
POST http://localhost:3001/v1/stage/create
Content-Type: application/json

{
    "stageType": 0,
    "caseId": "a78a707e-02b8-4580-954f-0dfb502e8c82"
}

### Get Stage by Stage ID
GET http://localhost:3001/v1/stage/59f4581b-4360-4f2a-be37-b516cfd330ff

### Get Stage by Case ID and Stage Type
GET http://localhost:3001/v1/stage/6248c90b-268b-46c4-b3f0-21547ddc1f20/0


### Update Stage by Stage ID
POST http://localhost:3001/v1/stage/update
Content-Type: application/json

{
    "stageId": "ee77a0d8-312e-4cf9-aaba-f558a611d920",
    "tasks": [
        "326d76a0-2286-4d5c-abdd-2058f9abd079",
        "9cc5e3dc-f648-44b5-8c72-62d9514cb57c",
        "c8d40298-939d-4db4-b09e-d12c6d7e9236",
        "53116a70-78cb-4df0-b908-840ed9f6cb2c",
        "aa2b5219-8c00-439d-a7ff-d5d097287134",
        "86d01134-d03c-417d-93e8-8bf83dd70385"
    ]
}

### Delete Stage by Stage ID
POST http://localhost:3001/v1/stage/delete
Content-Type: application/json

{
    "stageId": "2762c001-057b-44e9-bfe9-177ded53e626"
}


### Delete All Stages by Case ID
POST http://localhost:3001/v1/stage/delete/all
Content-Type: application/json

{
    "caseId": "0_e9a51f4a-ea7c-443d-9d66-e9d62bc41308_afa4ed13-f510-4edb-905b-ce9c12280ccc"
}
