### Register
POST http://localhost:3001/v1/auth/register
content-type: application/json

{
    "emailAddress": "eden@richtech-ai-labs.com",
    "password": "1234561341",
    "userName": "Eden Wu",
    "role": 1
}

### Login
POST http://localhost:3001/v1/auth/login
content-type: application/json

{
    "emailAddress": "verkho404@gmail.com",
    "password": "88888888"
}

### Delete User
POST http://localhost:3001/v1/auth/delete
content-type: application/json

{
    "emailAddress": "test1@gmail.com",
    "password": "1234561341"
}

### Update User
POST http://localhost:3001/v1/auth/update
content-type: application/json

{
    "emailAddress": "eden@richtech-ai-labs.com",
    "password": "1234561341",
    "userName": "John Doe",
    "role": 2,
    "uploadFolderName": "MG"
}

### Change password
POST http://localhost:3001/v1/auth/change-password
content-type: application/json

{
    "emailAddress": "eden@richtech-ai-labs.com",
    "currentPassword": "1234561341",
    "newPassword": "1234561342"
}