### Create Task Template
POST http://localhost:3001/v1/task-template/create
content-type: application/json

{
    "taskName": "Test Task 1",
    "creatorId": "verkho404@gmail.com",
    "stage": 1,
    "taskType": 0
}

### Create Task Template 2 b75f74e9-9bcd-40b4-ab9d-8084a5f3b0b8
POST http://localhost:3001/v1/task-template/create
content-type: application/json

{
    "taskName": "Test Task 2",
    "creatorId": "verkho404@gmail.com",
    "stage": 1,
    "taskType": 1,
    "prevTtid": "ffaf67eb-1938-4c6f-815c-ca6d21296918",
    "nextTtid": null
}

### Create Task Template 1.5
POST http://localhost:3001/v1/task-template/create
content-type: application/json

{
    "taskName": "Test Task 1.5",
    "creatorId": "verkho404@gmail.com",
    "stage": 1,
    "taskType": 2,
    "prevTtid": null,
    "nextTtid": "ffaf67eb-1938-4c6f-815c-ca6d21296918"
}


### Read Task Template By Stage
POST http://localhost:3001/v1/task-template/read/stage
content-type: application/json

{
    "stage": 0,
    "creatorId": "eden.wu@richtech-ai-lab.org"
}

### Delete Task Template
POST http://localhost:3001/v1/task-template/delete
content-type: application/json

{
    "ttid": "2338b625-c902-43c2-b5c2-1b77967789a4"
}

### Create Task Template With Template Objects
POST http://localhost:3001/v1/task-template/create/template
content-type: application/json

{
    "taskName": "Confirm case details",
    "taskType": 1,
    "templateObjs": [
        {
            "templateTitle": "[IMPORTANT] FEK Notice to Purchaser",
            "templateContent": "Dear {{customerName}},\n\nWe are writing to inform you that your order has been confirmed. Please find the details below:\n\nOrder ID: {{orderId}}\nOrder Date: {{orderDate}}\n\nThank you for shopping with us.\n\nSincerely,\n{{companyName}}"
        }
    ]
}

### Get Task Templates
POST http://localhost:3001/v1/task-template/read
content-type: application/json

{
    "taskName": "Confirm case details"
}


### Delete Task Template
POST http://localhost:3001/v1/task-template/delete
content-type: application/json

{
    "taskName": "Confirm case details"
}